//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpRequest.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaticValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelpRequest.Core.Resources.StaticValues", typeof(StaticValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^((([a-z]|\d|[!#\$%&amp;&apos;\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&amp;&apos;\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailErrorRegEx {
            get {
                return ResourceManager.GetString("EmailErrorRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /^[a-z0-9._%+-]+@[a-z0-9.-]+\.(?:[a-z]{2}|com|org|net|edu|gov|mil|biz|info|mobi|name|aero|asia|jobs|museum)$/.
        /// </summary>
        public static string EmailWarningRegEx {
            get {
                return ResourceManager.GetString("EmailWarningRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Support.
        /// </summary>
        public static string STR_ComputerSupport {
            get {
                return ResourceManager.GetString("STR_ComputerSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpRequest.
        /// </summary>
        public static string STR_HelpRequest {
            get {
                return ResourceManager.GetString("STR_HelpRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ticket has been successfully submitted, you will be receiving a confirmation email with a ticket # shortly (usually 5-10min)..
        /// </summary>
        public static string STR_HelpTicketSuccessfullySent {
            get {
                return ResourceManager.GetString("STR_HelpTicketSuccessfullySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming Support.
        /// </summary>
        public static string STR_ProgrammingSupport {
            get {
                return ResourceManager.GetString("STR_ProgrammingSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        public static string STR_UrgencyLevelCritical {
            get {
                return ResourceManager.GetString("STR_UrgencyLevelCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Critical Issue.
        /// </summary>
        public static string STR_UrgencyLevelNonCritical {
            get {
                return ResourceManager.GetString("STR_UrgencyLevelNonCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Requests.
        /// </summary>
        public static string STR_UrgencyLevelScheduledRequests {
            get {
                return ResourceManager.GetString("STR_UrgencyLevelScheduledRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workaround Available.
        /// </summary>
        public static string STR_UrgencyLevelWorkaroundAvailable {
            get {
                return ResourceManager.GetString("STR_UrgencyLevelWorkaroundAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Stoppage.
        /// </summary>
        public static string STR_UrgencyLevelWorkStoppage {
            get {
                return ResourceManager.GetString("STR_UrgencyLevelWorkStoppage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site Support.
        /// </summary>
        public static string STR_WebSiteSupport {
            get {
                return ResourceManager.GetString("STR_WebSiteSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&amp;&apos;\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WebSiteRegEx {
            get {
                return ResourceManager.GetString("WebSiteRegEx", resourceCulture);
            }
        }
    }
}
